const mongoose = require('mongoose');

const depreciationEntrySchema = new mongoose.Schema({
    assetId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Asset',
        required: true,
        index: true
    },
    date: {
        type: Date,
        required: true
    },
    depreciationAmount: {
        type: Number,
        required: true
    },
    openingBookValue: {
        type: Number,
        required: true
    },
    closingBookValue: {
        type: Number,
        required: true
    },
    method: {
        type: String,
        enum: ['SLM', 'DBM'],
        required: true
    },
    period: {
        month: Number,
        year: Number
    },
    isAutoGenerated: {
        type: Boolean,
        default: true
    },
    notes: String
}, {
    timestamps: true
});

// Index for quick lookup of an asset's depreciation history
depreciationEntrySchema.index({ assetId: 1, date: -1 });

module.exports = mongoose.model('AssetDepreciation', depreciationEntrySchema);
